### ISSUE TITLE
Add support for `allow=""`

### ISSUE THREAD

**Issue by thomaswilburn** [nprapps/sidechain#5]
Geolocation on third-party iframes, along with a number of other APIs, now needs the `allow` attribute to be set. See also: https://dev.chromium.org/Home/chromium-security/deprecating-permissions-in-cross-origin-iframes

Sidechain doesn't need to watch the allow attribute live, but it should check itself for this attribute before creating its internal iframe and setting the URL.

**Comment by mdemund-scpr** [comment]
Hi @thomaswilburn. Does this support include other parameters, like `clipboard-write`? I tried adding it but it doesn't work, but perhaps my syntax is incorrect or supplemental code is required

**Comment by thomaswilburn** [comment]
It is supported in the code but it looks to me like this version hasn't been deployed to npm yet. @alykat may be able to help us deploy, or if you're using it in projects as a part of a build process, you can source Sidechain from `nprapps/sidechain` (so that pulls from GitHub instead of NPM).

**Comment by mdemund-scpr** [comment]
@thomaswilburn Thank you for your response! I am currently pulling it in like so:
`import { Sidechain } from "@nprapps/sidechain"`

Does that mean it's pulling from npm or GH?

**Comment by thomaswilburn** [comment]
The @ at the start means that it's scoped to the npm organization, so that's coming from npm. If you remove it and reinstall using `npm install nprapps/sidechain`, I believe that will switch to the latest version from GH instead.

**Comment by mdemund-scpr** [comment]
So, actually the @ means it's coming from GH! I tried both ways, and am getting the same result. Is it possible to update the npm package?

**Comment by mdemund-scpr** [comment]
Perhaps the 'allow' update doesn't support clipboard-write/read?

**Comment by thomaswilburn** [comment]
The allow code is here: https://github.com/nprapps/sidechain/blob/master/src/index.js#L50 It's just a straight pass-through of the attribute on the sidechain element to the iframe in the shadow DOM, we're not checking the values at all. It may be worth verifying that this is the code you're actually seeing in your node_modules folder.

You can force a git-based install using `npm i git+https://github.com/nprapps/sidechain.git` if the non-@ install isn't working for you, and I verified that this does in fact include the correct permissions code.

The other thing I can think of is that the allow attribute needs to exist at the time that Sidechain checks the src attribute on startup. If it's being created by the parser in markup, all attributes should exist at the time that the attributeChangedCallback is executed, but if you're generating this dynamically (say, via JSX), I don't know if that's the case. This sounds dumb, but if you're using Sidechain in a framework, you might try swapping the order of the attributes to see if that influences attribute creation.

If neither of these work, and you can submit a test case using a Codepen or a gist or something, I can try to put in a fix this weekend. We could always move the `allow` attribute to be actively monitored instead of having it piggyback on `src` the way it is now.

**Comment by mdemund-scpr** [comment]
Thank you Thomas! 
It actually looks like it's a Chrome thing :/ 
There is an 'orphaned iframe error'.
Copying a link in my app using Safari works fine. 
I verified that I do in fact have your latest code--apologies for that.

**Comment by thomaswilburn** [comment]
Huh! That's wild to hear, and I'll look into it a little more, but I'm glad you have an answer to the problem.

**Comment by mdemund-scpr** [comment]
It's something to do with an extension I have installed!

**Comment by mdemund-scpr** [comment]
It's LastPass that is causing the issue! Our org is replacing it soon anyhow...so that's good. But it's interesting for you to know I'm sure.

**Comment by mdemund-scpr** [comment]
I don't know if this would be any help to you...but I came across this when looking up that error we were getting. 
[https://stackoverflow.com/questions/63521378/chrome-extension-extension-context-invalidated-when-getting-url/64407849#64407849](url)
I can share a screenshot of the error .... I'll send it via NewsNerdery on slack
